### ISSUE TITLE
可以处理截图吗

### ISSUE THREAD

**Issue by toxmc** [chishaxie/BlindWaterMark#4]
报错
image<hui.png> + image(encoded)<1.png> -> watermark<2.png>
Traceback (most recent call last):
  File "bwm.py", line 180, in <module>
    rwm = (f2 - f1) / alpha
ValueError: operands could not be broadcast together with shapes (744,794,3) (626,400,3)

**Comment by chishaxie** [comment]
你这个是两个图的尺寸不一致

**Comment by toxmc** [comment]
一张是生成图片的截图。要把截图的也转成一样大才能对比吗
